CREATE MATERIALIZED VIEW VW_MIHP_PROPERTY
BUILD IMMEDIATE
REFRESH complete
AS
SELECT 
HF.SHAPE,
HF.OBJECTID,
HF.CI_NUMBER,
HP.CI_NUMBER,
HP.MIHPNUMBER,
HP.PROPERTY_NAME,
HP.OWNERSHIP,
HP.FEDERAL_DESIGNATION,
HP.STATE_DESIGNATION,
HP.COUNTY_DESIGNATION,
HP.STATUS,
HP.OTHER_LANDMARK_NUM,
HP.LANDMARK_NUM,
HP.LANDMARK_BILL_NUM
FROM HISTORICFEATURESALL HF,HISTORIC_PROPERTY HP
WHERE HF.CI_NUMBER = HP.CI_NUMBER (+) AND
HP.STATUS = 'DEMOLISHED OR DESTROYED';

CREATE MATERIALIZED VIEW VW_DEMOLISHED_HISTORIC_ITEMS  
BUILD IMMEDIATE
REFRESH complete
AS
SELECT 
HF.SHAPE,
HF.OBJECTID,
HF.CI_NUMBER,
HP.CI_NUMBER,
HP.MIHPNUMBER,
HP.PROPERTY_NAME,
HP.OWNERSHIP,
HP.FEDERAL_DESIGNATION,
HP.STATE_DESIGNATION,
HP.COUNTY_DESIGNATION,
HP.STATUS,
HP.OTHER_LANDMARK_NUM,
HP.LANDMARK_NUM,
HP.LANDMARK_BILL_NUM
FROM HISTORICFEATURESALL HF,HISTORIC_PROPERTY HP
WHERE HF.CI_NUMBER = HP.CI_NUMBER (+) AND
HP.STATUS = 'DEMOLISHED OR DESTROYED';

CREATE MATERIALIZED VIEW VW_NRHP_PROPERTY  
BUILD IMMEDIATE
REFRESH complete
AS
SELECT 
HF.SHAPE,
HF.OBJECTID,
HF.CI_NUMBER,
HP.CI_NUMBER,
HP.MIHPNUMBER,
HP.PROPERTY_NAME,
HP.OWNERSHIP,
HP.FEDERAL_DESIGNATION,
HP.STATE_DESIGNATION,
HP.COUNTY_DESIGNATION,
HP.STATUS,
HP.OTHER_LANDMARK_NUM,
HP.LANDMARK_NUM,
HP.LANDMARK_BILL_NUM
FROM HISTORICFEATURESALL HF,HISTORIC_PROPERTY HP
WHERE HF.CI_NUMBER = HP.CI_NUMBER (+) AND
HP.STATUS = 'DEMOLISHED OR DESTROYED';

CREATE MATERIALIZED VIEW VW_LANDMARK_PROPERTY  
BUILD IMMEDIATE
REFRESH complete
AS
SELECT 
HF.SHAPE,
HF.OBJECTID,
HF.CI_NUMBER,
HP.CI_NUMBER,
HP.MIHPNUMBER,
HP.PROPERTY_NAME,
HP.OWNERSHIP,
HP.FEDERAL_DESIGNATION,
HP.STATE_DESIGNATION,
HP.COUNTY_DESIGNATION,
HP.STATUS,
HP.OTHER_LANDMARK_NUM,
HP.LANDMARK_NUM,
HP.LANDMARK_BILL_NUM
FROM HISTORICFEATURESALL HF,HISTORIC_PROPERTY HP
WHERE HF.CI_NUMBER = HP.CI_NUMBER (+) AND
HP.STATUS = 'DEMOLISHED OR DESTROYED';

