# Facilities views
DROP MATERIALIZED VIEW VW_CENTERLINE;
DROP MATERIALIZED VIEW VW_ADDRESS;
DROP MATERIALIZED VIEW VW_ADDRESS_UNIT;
DROP MATERIALIZED VIEW VW_ALIASSTREETNAME;
DROP MATERIALIZED VIEW VW_ALIASSTREETRANGE;
DROP MATERIALIZED VIEW VW_BILLIARDCLUBS;
DROP MATERIALIZED VIEW VW_FACILITY;
DROP MATERIALIZED VIEW VW_FACILITY_ADD;
DROP MATERIALIZED VIEW VW_FACILITY_USECODE;
DROP MATERIALIZED VIEW VW_FACILITY_UNIT;
DROP MATERIALIZED VIEW VW_HEALTHCENTERS;
DROP MATERIALIZED VIEW VW_INSTALLATION;
DROP MATERIALIZED VIEW VW_MOVIETHEATRES;
DROP MATERIALIZED VIEW VW_PALCENTERS;
DROP MATERIALIZED VIEW VW_SKATINGRINKS;
DROP MATERIALIZED VIEW VW_MAJOR_CENTERLINES;
DROP MATERIALIZED VIEW VW_RAILSTATIONS;
DROP MATERIALIZED VIEW VW_MAL_ID;
DROP MATERIALIZED VIEW VW_CLINE_ALIAS_OBJECTID;
DROP MATERIALIZED VIEW VW_CENTERLINE_ALIAS;
DROP MATERIALIZED VIEW VW_ADDR_ALIAS_OBJECTID;
DROP MATERIALIZED VIEW VW_ADDRESS_ALIAS;
DROP MATERIALIZED VIEW VW_ADDRESS_LINEAGE;
DROP VIEW VW_MAL_ID;
DROP VIEW VW_ALIASSTREETNAME;
DROP MATERIALIZED VIEW VW_FAC_POINT;
DROP MATERIALIZED VIEW VW_FACILITY_LABELS;
DROP VIEW VW_ADP_LABELS;
DROP MATERIALIZED VIEW VW_ADP_LABELS;
DROP VIEW VW_QC_STATUS;
DROP MATERIALIZED VIEW VW_QC_STATUS;

# Historic views
DROP MATERIALIZED VIEW VW_DESTROYED_HISTORIC_ITEMS;
DROP MATERIALIZED VIEW VW_LANDMARK_PROPERTY;
DROP MATERIALIZED VIEW VW_MHIP_PROPERTY;
DROP MATERIALIZED VIEW VW_NRHP_PROPERTY;

quit;
