REM Historic views
DROP MATERIALIZED VIEW VW_DEMOLISHED_HISTORIC_ITEMS;
DROP MATERIALIZED VIEW VW_LANDMARK_PROPERTY;
DROP MATERIALIZED VIEW VW_MIHP_PROPERTY;
DROP MATERIALIZED VIEW VW_NRHP_PROPERTY;

quit;
